Description: AWS Cloudformation For VPC Template
Mappings:
  AWSenvtoVPC:
    Growth-Dev:
      vpc: 10.0.0.0/24
    Growth-Prod:
      vpc: 10.2.0.0/25
    Growth-Stage:
      vpc: 10.1.0.0/25
Parameters:
  AWSenv:
    AllowedValues:
      - Growth-Dev
      - Growth-Stage
      - Growth-Prod
    Default: Growth-Dev
    Description: AWS Environment Type
    Type: String
Resources:
  AttachGateway:
    Properties:
      InternetGatewayId: !Ref 'InternetGateway'
      VpcId: !Ref 'VPC'
    Type: AWS::EC2::VPCGatewayAttachment
  InternetGateway:
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join
            - ''
            - - !Ref 'AWSenv'
              - -IG
    Type: AWS::EC2::InternetGateway
  MainRouteTable:
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Join
            - ''
            - - !Ref 'AWSenv'
              - -Public-RT
      VpcId: !Ref 'VPC'
    Type: AWS::EC2::RouteTable
  Route:
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'
      RouteTableId: !Ref 'MainRouteTable'
    Type: AWS::EC2::Route
  VPC:
    Properties:
      CidrBlock: !FindInMap
        - AWSenvtoVPC
        - !Ref 'AWSenv'
        - vpc
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref 'AWSenv'
    Type: AWS::EC2::VPC
