Description: AWS Cloudformation For VPC Template
Mappings:
  AWSenvtoVPC:
    Growth-Dev:
      vpc: 10.0.0.0/24
    Growth-Prod:
      vpc: 10.2.0.0/25
    Growth-Stage:
      vpc: 10.1.0.0/25
Parameters:
  AWSenv:
    AllowedValues:
      - Growth-Dev
      - Growth-Stage
      - Growth-Prod
    Default: Growth-Dev
    Description: AWS Environment Type
    Type: String
Resources:
  VPC:
    Properties:
      CidrBlock: 10.10.0.0/16
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
    Type: AWS::EC2::VPC
